### ISSUE TITLE
VERSION variable

### ISSUE THREAD

**Issue by kilimnik** [hhk7734/odroid_gpio#3]
I am using a module which relies on the Rpi.GPIO. This module uses the VERSION variable which is defined in the Rpi.GPIO library here https://sourceforge.net/p/raspberry-gpio-python/code/ci/default/tree/RPi/GPIO/__init__.py

It also would be great if the major and minor version from this and the Rpi library would be the same as some modules rely on specific versions and check try to check them.

**Comment by hhk7734** [comment]
What module do you use?

**Comment by kilimnik** [comment]
I am using a program called https://github.com/kantlivelong/OctoPrint-PSUControl.
And it checks here https://github.com/kantlivelong/OctoPrint-PSUControl/blob/71d8d4a259667ab9df3db34f995c055f40975836/octoprint_psucontrol/__init__.py#L283 what Version I have installed

**Comment by hhk7734** [comment]
Have you tried after adding VERSION?
There was no problem with compatibility?

**Comment by kilimnik** [comment]
I had no problems with it yet. The only problem is that I couldn't install it with pip because the requirements expect the Rpi.GPIO library. But this is nothing you can change
